#! /bin/sh

#### AUTOSTART ####
sxhkd &
~/.config/polybar/launch.sh &
nitrogen --restore &
dunst -config /home/atb43/.config/dunst/dunstrc_bspwm &
picom --config /home/atb43/.config/picom/picom.conf &
xset s off -dpms
xsetroot -cursor_name left_ptr &
dropbox start &



#### MONITORS ####
bspc monitor -d 1 2 3 4 5 6 7 8 9

#### BSPWM configuration ####
bspc config border_radius                 0
bspc config border_width                  2
bspc config window_gap                    8
bspc config top_padding                   34
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#232627"
bspc config active_border_color	              "#1793d0"
bspc config focused_border_color	      "#1793d0"
bspc config presel_feedback_color	      "#1793d0"
bspc config urgent_border_color 	      "#dd2727"

bspc config external_rules_command ~/.config/bspwm/external_rules
bspc rule -a mpv state=floating sticky=on
bspc rule -a zoom state=floating sticky=on
