#!/bin/bash

wid=$1
class=$2
instance=$3
consequences=$4

if [ "$class" = zoom ]; then
    title=$(xtitle "$wid")
    case "$title" in
        Zoom)
            echo "state=floating"
            echo "center=on"
            echo "sticky=on"
            ;;
    esac
fi
